#!/usr/bin/env python3

import argparse

from vcmean import MyApp as App

class Salan():
    def __init__(self):
        self.parser = argparse.ArgumentParser(
                description="calculate X to the power of Y")
        group = self.parser.add_mutually_exclusive_group()
        group.add_argument("-v", "--verbose", action="store_true")
        group.add_argument("-q", "--quiet", action="store_true")
        self.parser.add_argument("x", type=int, help="the base")
        self.parser.add_argument("y", type=int, help="the exponent")

    def run(self):
        args = self.parser.parse_args()
        answer = args.x**args.y
        if args.quiet:
            print(answer)
        elif args.verbose:
            print ("{} to the power {} equals {}".format(args.x, args.y, answer))
            self.openGUI()
        else:
            self.openGUI()
                
    def openGUI(self):
        app = App()
        app.MainLoop()





if __name__ == '__main__':
    salan = Salan()
    salan.run()
